version: '3.8'

services:
  mongo:
    image: mongo:latest
    restart: always
    env_file: ./.env
    ports:
      - $MONGO_PORT:$MONGO_PORT
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_ROOT_PASSWORD