version: '3.8'

services:
  mongo:
    image: mongo:latest
    restart: always
    env_file: ./.env
    ports:
      - $MONGO_PORT:$MONGO_PORT
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_ROOT_PASSWORD

  mongo-express:
    depends_on:
      - mongo
    image: mongo-express
    restart: always
    ports:
      - $MONGO_EXPRESS_PORT:$MONGO_EXPRESS_PORT
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_ROOT_USERNAME
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_ROOT_PASSWORD
      ME_CONFIG_MONGODB_URL: mongodb://$MONGO_ROOT_USERNAME:$MONGO_ROOT_PASSWORD@mongo:$MONGO_PORT/

  node:
    depends_on:
      - mongo
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    volumes:
      - ./server/:/usr/src/app
    restart: "no"      
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mongo
      - DB_USER=$MONGO_ROOT_USERNAME
      - DB_PASSWORD=$MONGO_ROOT_PASSWORD
    command: nodemon index.js
    stdin_open: true
    tty: true